"""initial schema

Revision ID: dbf34d521154
Revises: 
Create Date: 2026-05-15 00:13:44.577682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf34d521154'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_configs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('leveraged_etfs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('underlying', sa.String(), nullable=False),
    sa.Column('leverage_factor', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leveraged_etfs_id'), 'leveraged_etfs', ['id'], unique=False)
    op.create_index(op.f('ix_leveraged_etfs_ticker'), 'leveraged_etfs', ['ticker'], unique=True)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='tradeaction'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), server_default='0', nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('executed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_trades_date_id', 'trades', ['executed_at', 'id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_ticker'), 'trades', ['ticker'], unique=False)
    op.create_index('ix_trades_ticker_date_id', 'trades', ['ticker', 'executed_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trades_ticker_date_id', table_name='trades')
    op.drop_index(op.f('ix_trades_ticker'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index('ix_trades_date_id', table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_leveraged_etfs_ticker'), table_name='leveraged_etfs')
    op.drop_index(op.f('ix_leveraged_etfs_id'), table_name='leveraged_etfs')
    op.drop_table('leveraged_etfs')
    op.drop_table('app_configs')
    # ### end Alembic commands ###
