"""add index_trades table

Revision ID: e920117ef5cf
Revises: dbf34d521154
Create Date: 2026-05-15 00:40:59.452650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e920117ef5cf'
down_revision: Union[str, None] = 'dbf34d521154'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', name='tradeaction'), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), server_default='0', nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('executed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_index_trades_id'), 'index_trades', ['id'], unique=False)
    op.create_index(op.f('ix_index_trades_ticker'), 'index_trades', ['ticker'], unique=False)
    op.create_index('ix_index_trades_ticker_date_id', 'index_trades', ['ticker', 'executed_at', 'id'], unique=False)

    # Move existing index trades out of the trades table
    index_tickers = "('VOO', 'SPY', 'QQQ', 'IBIT', 'ETHA')"
    op.execute(f"""
        INSERT INTO index_trades (action, ticker, quantity, price, fees, platform, executed_at, created_at)
        SELECT action, ticker, quantity, price, fees, platform, executed_at, created_at
        FROM trades
        WHERE ticker IN {index_tickers}
    """)
    op.execute(f"DELETE FROM trades WHERE ticker IN {index_tickers}")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_index_trades_ticker_date_id', table_name='index_trades')
    op.drop_index(op.f('ix_index_trades_ticker'), table_name='index_trades')
    op.drop_index(op.f('ix_index_trades_id'), table_name='index_trades')
    op.drop_table('index_trades')
    # ### end Alembic commands ###
